# Generated by Django 2.2.9 on 2021-02-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210215_2337'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='post',
            order_with_respect_to='pub_date',
        ),
    ]
