# Generated by Django 2.2.6 on 2021-03-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210313_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='group',
            field=models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='posts.Group'),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
