# Generated by Django 2.2.6 on 2021-04-17 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20210417_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_post', to='posts.Post', verbose_name='Комментарий к посту'),
        ),
    ]
