# Generated by Django 2.2.6 on 2021-04-21 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0023_auto_20210421_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='author',
        ),
        migrations.AddField(
            model_name='follow',
            name='author',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='На кого подписываются'),
        ),
    ]
