# Generated by Django 2.2.6 on 2021-04-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20210422_1344'),
        ('posts', '0025_auto_20210422_2232'),
    ]

    operations = [
    ]
