# Generated by Django 2.2.6 on 2021-04-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_merge_20210423_0944'),
        ('posts', '0026_auto_20210423_2158'),
    ]

    operations = [
    ]
