# Generated by Django 2.2.6 on 2021-05-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20210428_2017'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follows',
        ),
    ]
